create table if not exists public.c0ld_roblox_fflag_state (
  scope_key text primary key,
  source_url text not null,
  settings_hash text not null,
  settings jsonb not null default '{}'::jsonb,
  setting_count integer not null default 0,
  checked_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.c0ld_roblox_fflag_events (
  id bigint generated by default as identity primary key,
  event_id text not null unique,
  scope_key text not null,
  source_url text not null,
  previous_hash text,
  current_hash text not null,
  added_keys jsonb not null default '[]'::jsonb,
  removed_keys jsonb not null default '[]'::jsonb,
  changed_keys jsonb not null default '[]'::jsonb,
  detected_at timestamptz not null,
  source text not null default 'schedule',
  raw_settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists c0ld_roblox_fflag_events_detected_idx
  on public.c0ld_roblox_fflag_events (detected_at desc);

create table if not exists public.c0ld_ps99_dev_blog_state (
  feed_key text primary key,
  feed_url text not null,
  latest_post_id text,
  latest_post_url text,
  checked_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.c0ld_ps99_dev_blog_events (
  id bigint generated by default as identity primary key,
  event_id text not null unique,
  post_id text not null,
  title text not null,
  url text not null,
  excerpt text,
  image_url text,
  published_at timestamptz,
  detected_at timestamptz not null,
  source text not null default 'schedule',
  raw_post jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists c0ld_ps99_dev_blog_events_detected_idx
  on public.c0ld_ps99_dev_blog_events (detected_at desc);

alter table public.c0ld_roblox_fflag_state enable row level security;
alter table public.c0ld_roblox_fflag_events enable row level security;
alter table public.c0ld_ps99_dev_blog_state enable row level security;
alter table public.c0ld_ps99_dev_blog_events enable row level security;

revoke all on table public.c0ld_roblox_fflag_state from anon, authenticated;
revoke all on table public.c0ld_roblox_fflag_events from anon, authenticated;
revoke all on table public.c0ld_ps99_dev_blog_state from anon, authenticated;
revoke all on table public.c0ld_ps99_dev_blog_events from anon, authenticated;

comment on table public.c0ld_roblox_fflag_state is
  'Latest public Roblox client-settings snapshot used for change detection.';
comment on table public.c0ld_roblox_fflag_events is
  'Detected changes to public Roblox client settings; this is not a private PS99 server-flag feed.';
comment on table public.c0ld_ps99_dev_blog_state is
  'Latest official BIG Games PS99 post observed by the alert worker.';
comment on table public.c0ld_ps99_dev_blog_events is
  'Official BIG Games PS99 posts detected after the initial baseline.';
