begin;

create extension if not exists pgcrypto;

create table if not exists public.discord_server_tracker_guilds (
  guild_id text primary key,
  channel_id text,
  message_id text,
  tracking_enabled boolean not null default false,
  default_place_id bigint not null default 8737899170,
  refresh_minutes integer not null default 10
    check (refresh_minutes between 1 and 60),
  last_refresh_at timestamptz,
  last_success_at timestamptz,
  last_error text,
  created_by_discord_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.discord_server_tracker_servers (
  id uuid primary key default gen_random_uuid(),
  guild_id text not null
    references public.discord_server_tracker_guilds(guild_id) on delete cascade,
  server_number integer not null check (server_number > 0),
  place_id bigint not null default 8737899170,
  vip_server_id text not null,
  access_code text,
  share_code text,
  server_link text not null,
  server_name text,
  owner_user_id bigint,
  owner_username text,
  is_active boolean not null default true,
  created_by_discord_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (guild_id, server_number),
  unique (guild_id, place_id, vip_server_id)
);

create table if not exists public.discord_server_tracker_observations (
  id bigint generated by default as identity primary key,
  tracked_server_id uuid not null
    references public.discord_server_tracker_servers(id) on delete cascade,
  guild_id text not null
    references public.discord_server_tracker_guilds(guild_id) on delete cascade,
  place_id bigint not null,
  vip_server_id text not null,
  job_id text,
  playing integer,
  max_players integer,
  players jsonb not null default '[]'::jsonb,
  player_tokens jsonb not null default '[]'::jsonb,
  clan_counts jsonb not null default '{}'::jsonb,
  fps numeric,
  ping numeric,
  status text not null
    check (status in ('online', 'offline', 'full', 'unavailable')),
  collection_error text,
  observed_at timestamptz not null default now(),
  raw_payload jsonb
);

create index if not exists discord_server_tracker_servers_guild_active_idx
  on public.discord_server_tracker_servers (guild_id, is_active, server_number);

create index if not exists discord_server_tracker_observations_server_time_idx
  on public.discord_server_tracker_observations (tracked_server_id, observed_at desc);

create index if not exists discord_server_tracker_observations_guild_time_idx
  on public.discord_server_tracker_observations (guild_id, observed_at desc);

create index if not exists discord_server_tracker_observations_vip_time_idx
  on public.discord_server_tracker_observations (place_id, vip_server_id, observed_at desc);

alter table public.discord_server_tracker_guilds enable row level security;
alter table public.discord_server_tracker_servers enable row level security;
alter table public.discord_server_tracker_observations enable row level security;

revoke all on table public.discord_server_tracker_guilds from anon, authenticated;
revoke all on table public.discord_server_tracker_servers from anon, authenticated;
revoke all on table public.discord_server_tracker_observations from anon, authenticated;

comment on table public.discord_server_tracker_guilds is
  'Per-Discord-guild private-server tracker settings and persistent message state.';
comment on table public.discord_server_tracker_servers is
  'Guild-scoped Roblox private servers keyed by stable vipServerId, never by transient Job ID.';
comment on table public.discord_server_tracker_observations is
  'Time-series Roblox private-server observations. Job IDs are observation data and may change.';

commit;
